import os

API_KEY = os.getenv("TRANSLATE_API_KEY", "sk-8487ef2c9c6d43dfbbf57246dfbad15f")
API_BASE_URL = "https://api.deepseek.com/v1"
API_MODEL = "deepseek-chat"

TRANSLATE_BATCH_SIZE = 30
TRANSLATE_CONTEXT_SIZE = 2
TRANSLATE_RETRY_TIMES = 3
TRANSLATE_RETRY_DELAY = 2

OCR_SAMPLE_FPS = 1
SUBTITLE_REGION = (0, 0.5, 1, 1)
OCR_LANG = "en"
OCR_USE_GPU = True
OCR_MIN_CONFIDENCE = 0.6
OCR_PREPROCESS = False
OCR_WATERMARK_RATIO = 0.4
OCR_MIN_TEXT_LENGTH = 2

OUTPUT_ENCODING = "utf-8"